# Generated by Django 3.1 on 2020-10-10 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 10, 59, 50, 440834)),
        ),
    ]
