# Generated by Django 3.1 on 2020-10-10 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20201010_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 14, 23, 51, 643485)),
        ),
    ]
